config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  resources :campaigns

  resources :banner, only: :index do
    get :click, on: :member
  end
  
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  validates :user_id, presence: true
  validates :name, presence: true
  validates :link, presence: true, url: true
  validates :image, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader

  after_create do
    data = {
      hits: 0,
      views: 0,
      link: link
    }.to_a.flatten
    Cache.redis.hmset cache_key, data
    Cache.redis.sadd "campaigns_list", id
  end

  after_update do
    Cache.redis.hset cache_key, :link, link
  end

  after_destroy do
    Cache.redis.del cache_key
    Cache.redis.srem "campaigns_list", id
  end

  def cache_key
    "campaigns:#{id}"
  end

  def get_counts
    counts = Cache.redis.hmget cache_key, "views", "hits"
    views, hits = counts.map(&:to_f)
    if views > 0
      conv = hits / views * 100
    elsif hits > 0
      conv = 100
    else
      conv = 0
    end
    return {
      views: views.to_i,
      hits: hits.to_i,
      conversion: conv.round
    }
  end

  class << self

    def random_id
      Cache.redis.srandmember("campaigns_list").to_i
    end

    def inc_views id
      Cache.redis.hincrby "campaigns:#{id}", "views", 1
    end

    def inc_hits id
      Cache.redis.hincrby "campaigns:#{id}", "hits", 1
    end

    def get_link id
      Cache.redis.hget "campaigns:#{id}", "link"
    end
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :rememberable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable, :validatable

  has_many :campaigns

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banner_controller.rb
class BannerController < ApplicationController
  protect_from_forgery except: :index

  def index
    respond_to do |format|
      format.js do
        @id = Campaign.random_id
        views = Campaign.inc_views @id
        WebsocketRails[@id].trigger :update_views, { views: views }
      end
    end
  end

  def click
    link = Campaign.get_link params[:id]
    if link
      hits = Campaign.inc_hits params[:id]
      WebsocketRails[params[:id].to_i].trigger :update_hits, { hits: hits }
      redirect_to link
    else
      raise NoCampaign
    end
  end

  class NoCampaign < StandardError; end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  def index
    @campaigns = current_user.campaigns
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new user: current_user
    @campaign.update_attributes campaign_params
    if @campaign.save
      redirect_to campaigns_path, notice: t('campaigns.campaign_created')
    else
      render :new
    end
  end

  def edit
    @campaign = current_user.campaigns.find params[:id]
  end

  def update
    @campaign = current_user.campaigns.find params[:id]
    if @campaign.update_attributes campaign_params
      redirect_to campaigns_path, notice: t('campaigns.campaign_updated')
    else
      render :edit
    end 
  end

  def destroy
    @campaign = current_user.campaigns.find params[:id]
    @campaign.destroy
    redirect_to campaigns_path, notice: t('campaigns.campaign_deleted')
  end

  def show
    @campaign = current_user.campaigns.find params[:id]
    @counts = @campaign.get_counts
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :link, :image)
  end
end

app/controllers/campaigns_ws_controller.rb
class CampaignsWsController < WebsocketRails::BaseController

  def authorize_channels
    channel = WebsocketRails[message[:channel]]
    unless current_user
      deny_channel(t(:access_denied))
    else
      if Campaign.exists?(id: channel.name, user_id: current_user.id)
        accept_channel current_user
      else
        deny_channel(t(:auth_failure))
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index; end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    html_msg = ""
    flash.each do |name, msg|
      case name.to_sym
      when :notice
        name = :success
      when :alert
        name = :danger
      when :error
        name = :danger
      end
      html_msg = content_tag :div, msg, :class => "alert alert-#{name}"
    end
    return html_msg
  end
  
end

app/helpers/banner_helper.rb
module BannerHelper

  def banner_hml_code id
    link_to click_banner_url(id: id) do
      image_tag root_url + "uploads/campaign/image/#{id}/banner.gif"
    end
  end

end

app/views/banner/index.js.erb
document.write("<%= escape_javascript(banner_hml_code(@id)) %>")

app/views/campaigns/_form.html.haml
= simple_form_for(@campaign, html: {class: 'form-horizontal'}, wrapper: :horizontal_form) do |f|
  = f.input :name
  = f.input :link
  = f.input :image

  .form-group
    .col-sm-offset-5= f.button :submit

app/views/campaigns/edit.html.haml
%h3= t('campaigns.edit_campaign')
%br/ 

= render 'form'

app/views/campaigns/index.html.haml
= render 'shared/embed_code'

= link_to new_campaign_path, class: 'btn btn-primary' do
  %span.glyphicon.glyphicon-plus
  = t('campaigns.add_campaign')
%br/
%br/

- unless @campaigns.empty?
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th= t('campaigns.name')
        %th= t('campaigns.link')
        %th= t('campaigns.actions')
    %tbody
    - @campaigns.each do |campaign|
      %tr
        %td= campaign.name
        %td= campaign.link
        %td
          .btn-group
            = link_to campaign_path(id: campaign.id), class: 'btn btn-xs btn-success' do
              %span.glyphicon.glyphicon-eye-open
              = t('campaigns.show')
            = link_to edit_campaign_path(id: campaign.id), class: 'btn btn-xs btn-info' do
              %span.glyphicon.glyphicon-pencil
              = t('campaigns.edit')
            = link_to campaign_path(id: campaign.id), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: t(:confirm) } do
              %span.glyphicon.glyphicon-trash
              = t('campaigns.delete')

app/views/campaigns/new.html.haml
%h3= t('campaigns.add_campaign')
%br/ 

= render 'form'

app/views/campaigns/show.html.haml
.page-header
  %h1
    = @campaign.name
    %small= link_to @campaign.link, @campaign.link, target: :blank

.well
  .row
    .col-md-6
      = image_tag(@campaign.image)
    .col-md-4
      %table.table.table-bordered.stats-table
        %tr
          %td.cap= t('campaigns.views')
          %td.count
            %span.badge{id: 'views_field'}= @counts[:views]
        %tr
          %td.cap= t('campaigns.hits')
          %td.count
            %span.badge{id: 'hits_field'}= @counts[:hits]
        %tr
          %td.cap= t('campaigns.conversion')
          %td.count
            %span.badge{id: 'conversion_field'}= "#{@counts[:conversion]}%"

= link_to :back, class: 'btn btn-default' do
  %span.glyphicon.glyphicon-circle-arrow-left
  = t(:back)

:coffee
  window.ws_channel = #{@campaign.id}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Banengine
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: "#{params[:controller]} #{params[:action]}"}
    .container
      = render 'shared/header'
      = flash_message
      = yield
      = render 'shared/footer'

app/views/shared/_embed_code.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title= t(:embed_code)
  .panel-body
    %code
      :escaped
        #{javascript_include_tag(banner_index_url(format: :js))}

app/views/shared/_footer.html.haml
.footer
  %p= t('footer.copyright')

app/views/shared/_header.html.haml
.header
  %ul.nav.nav-pills.pull-right
    %li{class: ("active" if params[:controller] == 'welcome')}= link_to t('header.home'), root_path
    - unless user_signed_in?
      %li{class: ("active" if params[:controller] == 'devise/sessions')}= link_to t('header.sign_in'), new_user_session_path
    - else
      %li{class: ("active" if params[:controller] == 'campaigns')}= link_to t('header.campaigns'), campaigns_path
      %li= link_to t('header.sign_out'), destroy_user_session_path, method: :delete
  %h3.text-muted= t(:title)

app/views/welcome/index.html.haml
.jumbotron
  %h1= t 'welcome.index.title'
  %p.lead= t('welcome.index.text').html_safe
  %p= link_to t('welcome.index.start'), campaigns_path, class: 'btn btn-lg btn-success'

= render 'shared/embed_code'